# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b189f61cb6774b3acb26d22cadd0d9b456fffab4ed7b32ba61ef2c47958200cdd26791c866aa01664112da2e165d807f3836116c1bf3af2af71f3a2000180d6

test:
  secret_key_base: e6d213e48e102100734c58aa2c818f0659b8faafe6664b05304a68939416f9a62deff2c62c3eea4f6e8f6ea460aab4e93f8dee193a9297f8db999443aa69aad1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8598edf47180b3b2204c31ef5ac35e41b3050cebb24b81f200350b778d8d4dffaaa3153d7e8fb9832eb5ce555dd87af7612562c654c86e697b69aec4739820ec
